POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "My fifhtyyy blog",
  "author": "Moikka Moi",
  "url": "blah blah blah",
  "likes": 3,
  "user": "5a93242aac0c2e9d468b97f6"
}